name: "Validate Gradle Wrapper"
on: [push]

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    if: github.repository == 'elastic/elasticsearch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # Release v3.5.0
